/**
 * The learning track. Every lesson here is real, written-out content —
 * there are no placeholder titles or generated filler.
 */

export type QuizQuestion = {
  q: string;
  options: string[];
  answer: number;
  /** Shown after answering, right or wrong. */
  why: string;
};

export type Lesson = {
  id: number;
  title: string;
  /** One line the user sees in the list. */
  hook: string;
  level: "Easy" | "Medium" | "Hard";
  minutes: number;
  /** Short paragraphs, plain language. */
  body: string[];
  /** The one thing to remember. */
  takeaway: string;
  quiz: QuizQuestion[];
};

export const LESSONS: Lesson[] = [
  {
    id: 1,
    title: "What is solar weather?",
    hook: "The Sun has weather, and it reaches us",
    level: "Easy",
    minutes: 2,
    body: [
      "We all know weather on Earth — rain, wind, storms. Space has weather too, and the Sun makes it.",
      "The Sun constantly throws out light, heat and a stream of tiny particles. Most of the time this is steady and harmless. But sometimes the Sun has an outburst and sends a huge burst of energy and particles our way.",
      "When that burst reaches Earth, it can shake our planet's magnetic shield. That's a solar storm. You won't feel it in your body, but the machines we rely on — satellites, GPS, radios, power lines — can feel it.",
      "That's what this app watches for. When something is coming, you'll know before it arrives, and you'll know what to do about it.",
    ],
    takeaway: "Solar weather is the Sun's activity reaching Earth. It doesn't hurt people, but it can disturb technology.",
    quiz: [
      {
        q: "What is solar weather?",
        options: [
          "Weather patterns caused by sunlight on Earth",
          "Conditions in space caused by activity on the Sun",
          "The temperature inside the Sun",
          "Seasonal changes in daylight",
        ],
        answer: 1,
        why: "Solar weather means the conditions in space between the Sun and Earth, driven by what the Sun is doing.",
      },
      {
        q: "Is a solar storm dangerous to your body?",
        options: [
          "Yes, you should stay indoors",
          "No — Earth's atmosphere and magnetic field protect us",
          "Only if you look at the Sun",
          "Only during the day",
        ],
        answer: 1,
        why: "On the ground you're well protected. The risk is to technology, not to people.",
      },
    ],
  },
  {
    id: 2,
    title: "The Sun's outbursts",
    hook: "Flares and the giant clouds that follow them",
    level: "Easy",
    minutes: 3,
    body: [
      "The Sun's surface is a churning mess of magnetic fields. Sometimes those fields snap and reconnect, like a stretched elastic band letting go. That release is a solar flare.",
      "A flare is a flash of energy. It travels at the speed of light, so it arrives in about eight minutes — there's no warning time at all. Flares mostly affect radio signals on the daylight side of Earth.",
      "Often a flare comes with something bigger: a coronal mass ejection, or CME. That's a colossal cloud of magnetised gas blasted off the Sun. It's slower — usually one to three days to reach us — which is why we can warn you in advance.",
      "A flare is the flash. A CME is the punch that may follow. The app tracks both.",
    ],
    takeaway: "Flares arrive in 8 minutes and disturb radio. CMEs take 1–3 days and cause the big storms.",
    quiz: [
      {
        q: "How long does a solar flare take to reach Earth?",
        options: ["About 8 minutes", "About 3 hours", "1 to 3 days", "About a week"],
        answer: 0,
        why: "Flares are light and radiation, so they travel at light speed — about 8 minutes from Sun to Earth.",
      },
      {
        q: "Why can we warn people about a CME but not a flare?",
        options: [
          "CMEs are brighter",
          "CMEs travel much slower, taking 1 to 3 days",
          "Flares are harmless",
          "Satellites can't see flares",
        ],
        answer: 1,
        why: "A CME is matter, not light, so it takes one to three days — that gap is our warning time.",
      },
    ],
  },
  {
    id: 3,
    title: "Earth's invisible shield",
    hook: "Why we're not fried every time the Sun sneezes",
    level: "Easy",
    minutes: 2,
    body: [
      "Earth has a magnetic field, generated by molten iron moving deep in its core. It surrounds the whole planet like an invisible bubble.",
      "When particles from the Sun arrive, this bubble deflects most of them around us. That's the single reason life on Earth's surface is possible.",
      "But the bubble isn't rigid. A strong burst from the Sun squashes and rattles it. That rattling is what we call a geomagnetic storm — and it's what induces unwanted currents in long wires and confuses satellites overhead.",
      "The shield never fails. It just wobbles, and our technology notices.",
    ],
    takeaway: "Earth's magnetic field deflects solar particles. When it gets rattled, that's a geomagnetic storm.",
    quiz: [
      {
        q: "What creates Earth's magnetic field?",
        options: [
          "The Moon's gravity",
          "Molten iron moving in Earth's core",
          "The atmosphere",
          "Solar panels",
        ],
        answer: 1,
        why: "Moving liquid iron in the outer core acts like a giant dynamo.",
      },
      {
        q: "What is a geomagnetic storm?",
        options: [
          "Heavy rain caused by the Sun",
          "A disturbance of Earth's magnetic field caused by solar activity",
          "A hole in the atmosphere",
          "A type of lightning",
        ],
        answer: 1,
        why: "It's the shaking of Earth's magnetic field when solar material hits it.",
      },
    ],
  },
  {
    id: 4,
    title: "Reading the storm scale",
    hook: "What the number on your dashboard means",
    level: "Easy",
    minutes: 3,
    body: [
      "The main number this app shows is called Kp. It runs from 0 to 9 and measures how much Earth's magnetic field is being shaken right now, averaged across the whole planet.",
      "0 to 3 is quiet — a completely normal day. 4 is unsettled, slightly bumpy but nothing to act on.",
      "5 and above is an actual storm. Forecasters relabel these as G1 (minor) through G5 (extreme). G1 is common and mostly means pretty auroras. G4 and G5 are rare and can genuinely affect power grids and navigation.",
      "You don't have to memorise any of this. The app always tells you in words what the number means and whether you need to do anything.",
    ],
    takeaway: "Kp runs 0–9. Below 4 is calm, 5 and up is a storm, and the app translates it for you.",
    quiz: [
      {
        q: "A Kp reading of 2 means...",
        options: ["A severe storm", "Conditions are quiet and normal", "GPS will fail", "Aurora everywhere"],
        answer: 1,
        why: "Anything under 4 is a normal, quiet day.",
      },
      {
        q: "At what Kp value does an actual storm begin?",
        options: ["2", "3", "5", "9"],
        answer: 2,
        why: "Kp 5 is the threshold for a G1 minor geomagnetic storm.",
      },
      {
        q: "What does G5 mean?",
        options: ["A mild storm", "An extreme storm, very rare", "Good conditions", "No data"],
        answer: 1,
        why: "The G-scale runs G1 minor to G5 extreme. G5 events happen only a few times per solar cycle.",
      },
    ],
  },
  {
    id: 5,
    title: "Why your GPS drifts",
    hook: "The layer of sky that bends satellite signals",
    level: "Medium",
    minutes: 3,
    body: [
      "GPS works by timing signals from satellites 20,000 km up. Your phone measures how long each signal took and works out where you are.",
      "Those signals pass through the ionosphere — an electrically charged layer of the upper atmosphere. Charged air slows the signals slightly, and GPS receivers correct for the usual amount of slowing.",
      "During a solar storm, the ionosphere gets stirred up and unpredictable. The correction is suddenly wrong, so your position can drift by metres — occasionally tens of metres.",
      "For walking around town, you won't care. For surveying, farming with auto-steer, drone flying, aviation or marine navigation, it matters a great deal.",
    ],
    takeaway: "Storms stir up the ionosphere, which distorts GPS timing and pushes your position off by metres.",
    quiz: [
      {
        q: "Which layer of the atmosphere affects GPS signals during storms?",
        options: ["The troposphere", "The ionosphere", "The ozone layer", "The stratosphere"],
        answer: 1,
        why: "The ionosphere is electrically charged, and storms make its effect on signals unpredictable.",
      },
      {
        q: "Who is most affected by GPS drift during a storm?",
        options: [
          "Someone walking to a shop",
          "A surveyor or a pilot needing precise positions",
          "Someone watching TV",
          "Nobody",
        ],
        answer: 1,
        why: "Everyday navigation tolerates a few metres of error. Precision work does not.",
      },
    ],
  },
  {
    id: 6,
    title: "Radio blackouts",
    hook: "Why long-distance radio goes quiet after a flare",
    level: "Medium",
    minutes: 3,
    body: [
      "Long-distance radio — the kind used by ships, aircraft on ocean routes, emergency services and amateur operators — works by bouncing signals off the ionosphere and back down over the horizon.",
      "When a strong flare hits, its X-rays make the lowest part of the ionosphere far more absorbent. Instead of bouncing, signals get soaked up and vanish.",
      "This is a radio blackout. It affects only the half of Earth in daylight at that moment, and it typically lasts minutes to a couple of hours.",
      "It's rated R1 (minor) to R5 (extreme), and it's driven by the flare's class — M-class flares cause noticeable fades, X-class can wipe out the band completely.",
    ],
    takeaway: "Flare X-rays make the lower ionosphere absorb radio instead of reflecting it, silencing long-distance bands on the daylight side.",
    quiz: [
      {
        q: "Why do radio blackouts only affect part of the planet?",
        options: [
          "Only some countries have radios",
          "Only the daylight side is hit by the flare's X-rays",
          "Radio only works at night",
          "Satellites block it",
        ],
        answer: 1,
        why: "X-rays travel in a straight line from the Sun, so only the sunlit hemisphere is affected.",
      },
      {
        q: "Which flare class causes the most severe radio blackouts?",
        options: ["A-class", "C-class", "M-class", "X-class"],
        answer: 3,
        why: "The scale runs A, B, C, M, X — with X the strongest.",
      },
    ],
  },
  {
    id: 7,
    title: "Storms and the power grid",
    hook: "How space weather reaches a wall socket",
    level: "Medium",
    minutes: 3,
    body: [
      "A changing magnetic field induces electric current in any long conductor. Power transmission lines are hundreds of kilometres of exactly that.",
      "During a strong geomagnetic storm, slow direct current gets pushed into a grid designed only for alternating current. Transformers don't like it — they heat up, hum, and in severe cases fail.",
      "In March 1989 a storm collapsed the entire Quebec power grid in about 90 seconds, leaving six million people without electricity for nine hours.",
      "Grid operators now watch the same forecasts you're looking at, and can reduce load or reconfigure the network ahead of a big event. Blackouts from space weather are rare — but they're a real, documented risk.",
    ],
    takeaway: "Storms induce stray currents in long power lines, which stresses transformers and can, rarely, cause blackouts.",
    quiz: [
      {
        q: "What happened in Quebec in March 1989?",
        options: [
          "An aurora was photographed",
          "A geomagnetic storm collapsed the power grid",
          "A satellite was lost",
          "GPS was invented",
        ],
        answer: 1,
        why: "The 1989 storm blacked out Quebec in about 90 seconds — the classic example of grid impact.",
      },
      {
        q: "Why are power lines vulnerable?",
        options: [
          "They're made of plastic",
          "They're very long conductors, so changing magnetic fields induce currents in them",
          "They're above ground",
          "They carry too much voltage",
        ],
        answer: 1,
        why: "Length is what matters — a changing field induces current along the whole span.",
      },
    ],
  },
  {
    id: 8,
    title: "The northern lights",
    hook: "The one part of a storm you actually want",
    level: "Easy",
    minutes: 2,
    body: [
      "When solar particles funnel down Earth's magnetic field lines near the poles, they smash into atoms of oxygen and nitrogen high in the atmosphere. Those atoms glow.",
      "Oxygen at around 100 km gives the familiar green. Higher up it glows red. Nitrogen contributes blues and purples along the lower edges.",
      "The stronger the storm, the further from the poles the glow reaches. In a big event, aurora has been seen from Mexico, Spain and northern India.",
      "To actually see it: get away from streetlights, look toward the pole, let your eyes adjust for twenty minutes, and be patient. A phone camera on night mode will often pick it up before your eyes do.",
    ],
    takeaway: "Aurora is solar particles making the upper atmosphere glow. Bigger storms push it further from the poles.",
    quiz: [
      {
        q: "What colour does oxygen glow at around 100 km altitude?",
        options: ["Blue", "Green", "Yellow", "White"],
        answer: 1,
        why: "That green is the signature aurora colour, from oxygen at roughly 100 km.",
      },
      {
        q: "What's the best way to see an aurora?",
        options: [
          "Look at the Sun",
          "Go somewhere dark, look toward the pole, and let your eyes adjust",
          "Use binoculars in a city centre",
          "Wait for midday",
        ],
        answer: 1,
        why: "Darkness and dark-adapted eyes matter more than any equipment.",
      },
    ],
  },
  {
    id: 9,
    title: "The Sun's 11-year rhythm",
    hook: "Why some years are stormier than others",
    level: "Medium",
    minutes: 3,
    body: [
      "The Sun's magnetic field flips over roughly every 11 years, and its activity rises and falls with that cycle.",
      "At solar minimum the Sun's face is nearly blank and storms are rare. At solar maximum it's covered in sunspots and outbursts come thick and fast.",
      "We're in Solar Cycle 25, which peaked around 2024–2025. That means elevated activity for the next few years — more storms, more aurora, and more reason to keep an eye on forecasts.",
      "Sunspots are the visible marker. They're cooler, darker patches where intense magnetic fields poke through the surface, and they're where most flares begin.",
    ],
    takeaway: "Solar activity cycles every ~11 years. We're near the peak of Cycle 25, so storms are more frequent now.",
    quiz: [
      {
        q: "How long is the solar cycle?",
        options: ["1 year", "About 11 years", "50 years", "100 years"],
        answer: 1,
        why: "Roughly 11 years from one minimum to the next.",
      },
      {
        q: "What are sunspots?",
        options: [
          "Holes in the Sun",
          "Cooler, darker areas of intense magnetic field where flares often start",
          "Reflections in the telescope",
          "Clouds on the Sun",
        ],
        answer: 1,
        why: "They're magnetically intense regions — cooler, so they look dark, and they're flare factories.",
      },
    ],
  },
  {
    id: 10,
    title: "The Carrington Event",
    hook: "The biggest storm ever recorded, in 1859",
    level: "Medium",
    minutes: 3,
    body: [
      "On 1 September 1859, English astronomer Richard Carrington watched a brilliant white flash erupt from a sunspot group. Within about 17 hours, Earth was hit by the most powerful geomagnetic storm on record.",
      "Aurora appeared as far south as Cuba and Hawaii. It was reportedly bright enough to read a newspaper by at midnight, and some people got up thinking it was dawn.",
      "The world's only electrical infrastructure at the time was the telegraph. Operators got shocks from their equipment. Some lines threw sparks and set paper alight. Others kept working with their batteries disconnected entirely, running on induced current alone.",
      "A Carrington-class event today would be far more disruptive, because far more of what we depend on is electrical. This is exactly why space weather forecasting exists.",
    ],
    takeaway: "The 1859 Carrington Event is the strongest storm on record — it set telegraph offices alight and lit up the sky worldwide.",
    quiz: [
      {
        q: "What technology was disrupted in 1859?",
        options: ["Radio", "The telegraph network", "Television", "The internet"],
        answer: 1,
        why: "The telegraph was the only electrical network then — and operators were shocked by their own equipment.",
      },
      {
        q: "How long after the flare did the storm hit Earth?",
        options: ["8 minutes", "About 17 hours", "3 days", "A week"],
        answer: 1,
        why: "Unusually fast for a CME — about 17 hours, which is part of what made it so severe.",
      },
    ],
  },
  {
    id: 11,
    title: "Satellites in the firing line",
    hook: "What storms do 400 km above your head",
    level: "Hard",
    minutes: 4,
    body: [
      "Satellites have no atmosphere to hide behind, so they take solar weather directly.",
      "Three things go wrong. Energetic particles can flip bits in memory, causing glitches or resets. Charge builds up unevenly on the spacecraft body and discharges like a tiny lightning strike, damaging electronics. And solar panels degrade a little more with every storm.",
      "There's a fourth, sneakier effect. A storm heats and puffs up the upper atmosphere, so satellites in low orbit suddenly meet more drag. They slow down and drop.",
      "In February 2022, SpaceX lost 38 Starlink satellites this way — launched into a modest storm, they couldn't climb against the extra drag and re-entered.",
      "Operators respond by putting spacecraft into safe mode, delaying manoeuvres, and postponing launches when a storm is forecast.",
    ],
    takeaway: "Storms flip bits, charge spacecraft, degrade panels — and thicken the upper atmosphere enough to drag satellites down.",
    quiz: [
      {
        q: "How did a 2022 storm destroy 38 Starlink satellites?",
        options: [
          "It exploded them",
          "It heated the upper atmosphere, increasing drag so they couldn't reach orbit",
          "It blocked their radio",
          "It drained their batteries",
        ],
        answer: 1,
        why: "The storm puffed up the atmosphere; the extra drag pulled the newly launched satellites back down.",
      },
      {
        q: "What is a 'single event upset'?",
        options: [
          "A satellite launch",
          "A particle flipping a bit in a computer's memory",
          "A solar eclipse",
          "A ground station failure",
        ],
        answer: 1,
        why: "A single energetic particle can flip a memory bit and corrupt data or crash a system.",
      },
    ],
  },
  {
    id: 12,
    title: "Flying through a storm",
    hook: "Why planes get rerouted away from the poles",
    level: "Hard",
    minutes: 3,
    body: [
      "Polar flight routes are the shortest path between, say, New York and Hong Kong. They're also the most exposed to space weather, because Earth's magnetic field funnels particles down at the poles.",
      "Two problems arise. Long-distance radio — the only way to talk to controllers over the pole, where there's no satellite coverage — can black out. And radiation dose at altitude rises, which matters for crew who fly those routes constantly.",
      "So during a strong event, airlines shift flights to lower latitudes. That costs fuel, time and money, and occasionally means an extra refuelling stop.",
      "Aircrew are classified as radiation workers in many countries for exactly this reason, and their cumulative dose is tracked.",
    ],
    takeaway: "Polar routes lose radio contact and see higher radiation during storms, so airlines reroute south at real cost.",
    quiz: [
      {
        q: "Why are polar flight routes especially affected?",
        options: [
          "It's colder there",
          "Earth's magnetic field funnels solar particles toward the poles, and there's no satellite radio coverage",
          "Planes fly higher there",
          "There are more airports",
        ],
        answer: 1,
        why: "Both the particle funnelling and the reliance on HF radio make the poles the vulnerable spot.",
      },
    ],
  },
  {
    id: 13,
    title: "How forecasts are made",
    hook: "The spacecraft standing guard between us and the Sun",
    level: "Hard",
    minutes: 4,
    body: [
      "Forecasting starts with watching the Sun. Solar telescopes track sunspot groups and measure how twisted their magnetic fields are — the more twisted, the more likely a flare.",
      "When a CME launches, coronagraphs image the expanding cloud and forecasters estimate its speed and direction. That gives a rough arrival time, usually accurate to within about six hours.",
      "The decisive measurement comes from spacecraft parked at a point called L1, about 1.5 million km sunward of Earth — DSCOVR and ACE. The solar wind reaches them roughly 15 to 60 minutes before it reaches us.",
      "That's the real warning. They measure the cloud's speed and, crucially, which way its magnetic field points. If it points south, opposite to Earth's, the two fields link up and energy pours in. If it points north, the same cloud may pass almost harmlessly.",
      "That single measurement — southward or not — is the difference between a quiet night and a major storm. It's why forecasts firm up dramatically in the final hour.",
    ],
    takeaway: "Spacecraft at L1 sample the solar wind 15–60 minutes early; whether its magnetic field points south decides how bad the storm gets.",
    quiz: [
      {
        q: "How much warning do L1 spacecraft give?",
        options: ["Several days", "Roughly 15 to 60 minutes", "About 8 minutes", "A week"],
        answer: 1,
        why: "They sit 1.5 million km upstream, which the solar wind crosses in 15–60 minutes depending on its speed.",
      },
      {
        q: "What makes a CME hit hard rather than pass harmlessly?",
        options: [
          "Its colour",
          "Its magnetic field pointing south, opposite to Earth's",
          "The time of day",
          "Its distance from the Moon",
        ],
        answer: 1,
        why: "A southward field links with Earth's and lets energy pour in. A northward one largely deflects.",
      },
    ],
  },
  {
    id: 14,
    title: "Your own storm plan",
    hook: "Five minutes of prep, and you're set",
    level: "Easy",
    minutes: 3,
    body: [
      "You don't need a bunker. Solar storms are an inconvenience for most people, not an emergency — but a little preparation removes the inconvenience entirely.",
      "Before a storm arrives: charge your phone and a power bank, download offline maps for anywhere you'll travel, and note down any address or number you'd normally look up online.",
      "During a strong storm: don't trust satnav for anything precise, expect calls and data to be normal but radio to be patchy, and be ready for brief power flickers if you're on a rural grid.",
      "If you use anything that depends on precise positioning or long-distance radio for work — surveying, farming, flying, sailing, emergency response — check the forecast the way you'd check the weather, and plan around the worst hours.",
      "Then go outside and look up. If the storm is strong enough to be a nuisance, it's probably strong enough to be beautiful.",
    ],
    takeaway: "Charge up, download maps offline, don't rely on precise GPS during the peak — and enjoy the aurora.",
    quiz: [
      {
        q: "What's the most useful thing to do before a forecast storm?",
        options: [
          "Turn off your phone for a day",
          "Charge devices and download offline maps",
          "Unplug your fridge",
          "Stay indoors",
        ],
        answer: 1,
        why: "Charged devices and offline maps cover almost every practical inconvenience a storm causes.",
      },
      {
        q: "During a strong storm, what should you not fully rely on?",
        options: ["Your fridge", "Precise GPS navigation", "Your kettle", "Printed maps"],
        answer: 1,
        why: "GPS accuracy is the thing that visibly degrades. Printed and offline maps are unaffected.",
      },
    ],
  },
];

export const LEVEL_COLOR: Record<Lesson["level"], string> = {
  Easy: "#2dd4bf",
  Medium: "#ff9f43",
  Hard: "#ff5d6c",
};

export function findLesson(query: string): Lesson | null {
  const q = query.toLowerCase().trim();
  const byNumber = Number(q);
  if (Number.isFinite(byNumber)) {
    const hit = LESSONS.find((l) => l.id === byNumber);
    if (hit) return hit;
  }
  return (
    LESSONS.find((l) => l.title.toLowerCase().includes(q)) ??
    LESSONS.find((l) => q.split(/\s+/).some((w) => w.length > 3 && l.title.toLowerCase().includes(w))) ??
    LESSONS.find((l) => l.body.join(" ").toLowerCase().includes(q)) ??
    null
  );
}
